title: Status
subtitle: "A new kind of tool for a new kind of internet"
description: "Status is the mobile windown onto Ethereum, the platform with which we will onboard the first million users of a truly distributed web."
author: Status
language: en
timezone: UTC

url: https://dev-docs.status.im/
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy
deploy:
  type: git
  branch: gh-pages
  name: status-im-auto
  repo: git@github.com:status-im/docs.status.im.git

theme_config:
    favicon: img/logo-32.png

highlight:
  enable: true
  line_number: false

disqus_shortname: hexojs
twitter: ethstatus
github: staus-im
