title: Nimbus
subtitle: "Light clients for everyone!"
description: "Nimbus is a research project and a client implementation for Ethereum 2.0 designed to perform well on embedded systems and personal mobile devices, including older smartphones with resource-restricted hardware."
author: Nimbus
language: en
timezone: UTC

url: https://dev-nimbus.status.im/
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy
deploy:
  type: git
  branch: gh-pages
  name: status-im-auto
  repo: git@github.com:status-im/nimbus.status.im.git

theme_config:
    favicon: img/favicon.png

highlight:
  enable: true
  line_number: false

disqus_shortname: hexojs
twitter: ethstatus
github: status-im
